const sampleMovies = [
  {
    title: "El Padrino",
    description: "La saga de la familia Corleone, una poderosa dinastía criminal de Nueva York. Don Vito Corleone, el patriarca, debe decidir si entregar el negocio familiar a su hijo menor Michael, quien inicialmente no quería nada que ver con los negocios familiares.",
    shortDescription: "La épica saga de la familia Corleone y su imperio criminal en Nueva York.",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre: ["Drama", "Crimen"],
    year: 1972,
    duration: 175,
    rating: 9.2,
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
    trailer: "https://www.youtube.com/watch?v=sY1S34973zA"
  },
  {
    title: "El Señor de los Anillos: La Comunidad del Anillo",
    description: "Un hobbit llamado Frodo hereda un anillo mágico que podría salvar o destruir el mundo. Con la ayuda de un grupo de amigos, emprende un viaje épico para destruir el anillo en el Monte del Destino.",
    shortDescription: "Frodo emprende un viaje épico para destruir el Anillo Único y salvar la Tierra Media.",
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre: ["Aventura", "Fantasía", "Acción"],
    year: 2001,
    duration: 178,
    rating: 8.8,
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Orlando Bloom", "Viggo Mortensen"],
    trailer: "https://www.youtube.com/watch?v=V75dMMIW2B4"
  },
  {
    title: "Pulp Fiction",
    description: "Historias entrelazadas de criminales, boxeadores y gángsters en Los Ángeles. La película presenta múltiples narrativas no lineales que se conectan de manera sorprendente.",
    shortDescription: "Historias entrelazadas de criminales en Los Ángeles con narrativa no lineal.",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg",
    genre: ["Crimen", "Drama"],
    year: 1994,
    duration: 154,
    rating: 8.9,
    director: "Quentin Tarantino",
    cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
    trailer: "https://www.youtube.com/watch?v=s7EdQ4FqbhY"
  },
  {
    title: "Matrix",
    description: "Un programador de computadoras descubre que la realidad que conoce es una simulación creada por máquinas inteligentes que han esclavizado a la humanidad. Debe elegir entre la verdad dolorosa y la ignorancia feliz.",
    shortDescription: "Neo descubre que la realidad es una simulación y debe luchar contra las máquinas.",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7u3pxc0K1wx32IleAkLv78MKgrw.jpg",
    genre: ["Acción", "Ciencia ficción"],
    year: 1999,
    duration: 136,
    rating: 8.7,
    director: "Lana Wachowski, Lilly Wachowski",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    trailer: "https://www.youtube.com/watch?v=m8e-FF8MsqU"
  },
  {
    title: "Titanic",
    description: "Una joven aristócrata se enamora de un artista pobre a bordo del RMS Titanic durante su viaje inaugural. Su romance se ve interrumpido cuando el barco choca con un iceberg.",
    shortDescription: "Una historia de amor épica a bordo del Titanic durante su viaje inaugural.",
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yDI6D5ZQh67e4dZkOj3t3g3T4dU.jpg",
    genre: ["Romance", "Drama"],
    year: 1997,
    duration: 194,
    rating: 7.9,
    director: "James Cameron",
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
    trailer: "https://www.youtube.com/watch?v=2e-eXJ6HgkQ"
  },
  {
    title: "El Rey León",
    description: "Simba, un joven león, debe aprender a asumir su destino como rey después de que su padre es asesinado por su tío Scar. Con la ayuda de nuevos amigos, regresa para reclamar su reino.",
    shortDescription: "Simba debe aprender a ser rey después de la muerte de su padre.",
    poster: "https://image.tmdb.org/t/p/w500/1M876Kp7lVl6sVvBc8X7sKp3QzO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg",
    genre: ["Animación", "Familia", "Drama"],
    year: 1994,
    duration: 88,
    rating: 8.5,
    director: "Roger Allers, Rob Minkoff",
    cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones", "Moira Kelly"],
    trailer: "https://www.youtube.com/watch?v=4sj1MT05lAA"
  },
  {
    title: "Avengers: Endgame",
    description: "Después de que Thanos destruye la mitad del universo, los Vengadores restantes deben reunirse para revertir el daño y restaurar el orden en el universo.",
    shortDescription: "Los Vengadores se reúnen para revertir el daño causado por Thanos.",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    year: 2019,
    duration: 181,
    rating: 8.4,
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c"
  },
  {
    title: "Parásitos",
    description: "Una familia pobre que vive en un sótano encuentra trabajo con una familia rica, pero sus planes se complican cuando intentan infiltrarse completamente en sus vidas.",
    shortDescription: "Una familia pobre se infiltra en la vida de una familia adinerada.",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    genre: ["Drama", "Thriller"],
    year: 2019,
    duration: 132,
    rating: 8.6,
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    trailer: "https://www.youtube.com/watch?v=isOGD_7hNIY"
  },
  {
    title: "Dune",
    description: "Paul Atreides, un joven brillante y talentoso, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su pueblo.",
    shortDescription: "Paul Atreides debe viajar a un planeta peligroso para asegurar el futuro de su pueblo.",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/61X2LQ6P9gW5j3E1ZJ6KzF9Z2Y8.jpg",
    genre: ["Ciencia ficción", "Aventura"],
    year: 2021,
    duration: 155,
    rating: 8.0,
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Josh Brolin"],
    trailer: "https://www.youtube.com/watch?v=n9xhJrPXop4"
  },
  {
    title: "Top Gun: Maverick",
    description: "Después de más de treinta años de servicio, Pete 'Maverick' Mitchell sigue siendo uno de los mejores pilotos de la Armada. Debe enfrentar su pasado mientras entrena a una nueva generación de pilotos.",
    shortDescription: "Maverick regresa para entrenar a una nueva generación de pilotos de élite.",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    genre: ["Acción", "Drama"],
    year: 2022,
    duration: 130,
    rating: 8.3,
    director: "Joseph Kosinski",
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
    trailer: "https://www.youtube.com/watch?v=qSqVVswa420"
  },
  {
    title: "El Caballero de la Noche",
    description: "Batman debe aceptar una de las mayores pruebas psicológicas y físicas cuando el Joker emerge del inframundo criminal para sumir Gotham en la anarquía.",
    shortDescription: "Batman enfrenta al Joker en una batalla por el alma de Gotham City.",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    genre: ["Acción", "Crimen", "Drama"],
    year: 2008,
    duration: 152,
    rating: 9.0,
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY"
  },
  {
    title: "Forrest Gump",
    description: "La vida de Forrest Gump, un hombre con un coeficiente intelectual bajo pero con un gran corazón, quien sin querer se convierte en testigo de varios momentos históricos de Estados Unidos.",
    shortDescription: "Un hombre extraordinario vive una vida increíble siendo testigo de la historia.",
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7c9UVPPiTPltouxRVY6N9uUaM3p.jpg",
    genre: ["Drama", "Romance"],
    year: 1994,
    duration: 142,
    rating: 8.8,
    director: "Robert Zemeckis",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg"
  },
  {
    title: "Inception",
    description: "Un ladrón que roba secretos corporativos a través de la tecnología de compartir sueños recibe la tarea inversa de plantar una idea en la mente de un CEO.",
    shortDescription: "Un ladrón de sueños debe plantar una idea en la mente de un CEO.",
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    genre: ["Acción", "Ciencia ficción", "Thriller"],
    year: 2010,
    duration: 148,
    rating: 8.8,
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0"
  },
  {
    title: "Interestelar",
    description: "Un grupo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.",
    shortDescription: "Exploradores viajan por el espacio para salvar a la humanidad.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
    genre: ["Aventura", "Drama", "Ciencia ficción"],
    year: 2014,
    duration: 169,
    rating: 8.6,
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E"
  },
  {
    title: "El Padrino II",
    description: "La continuación de la saga de la familia Corleone, que presenta historias paralelas: el ascenso de Vito Corleone y la expansión del imperio de Michael.",
    shortDescription: "El ascenso de Vito y la expansión del imperio de Michael Corleone.",
    poster: "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/gLbBRyS7UB0D8ypuRsJL7ad6wBw.jpg",
    genre: ["Drama", "Crimen"],
    year: 1974,
    duration: 202,
    rating: 9.0,
    director: "Francis Ford Coppola",
    cast: ["Al Pacino", "Robert De Niro", "Robert Duvall", "Diane Keaton"],
    trailer: "https://www.youtube.com/watch?v=9O1Iy9mag_4"
  },
  {
    title: "La Lista de Schindler",
    description: "En la Polonia ocupada por los nazis durante la Segunda Guerra Mundial, el industrial Oskar Schindler se preocupa por sus trabajadores judíos después de presenciar su persecución.",
    shortDescription: "Un industrial salva a más de mil judíos durante el Holocausto.",
    poster: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    genre: ["Drama", "Historia", "Guerra"],
    year: 1993,
    duration: 195,
    rating: 9.0,
    director: "Steven Spielberg",
    cast: ["Liam Neeson", "Ben Kingsley", "Ralph Fiennes", "Caroline Goodall"],
    trailer: "https://www.youtube.com/watch?v=gG22XNhtnoY"
  },
  {
    title: "El Silencio de los Inocentes",
    description: "Una joven cadete del FBI busca la ayuda de un asesino en serie encarcelado para capturar a otro asesino que despelleja a sus víctimas.",
    shortDescription: "Una agente del FBI busca la ayuda de Hannibal Lecter para atrapar a un asesino.",
    poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7NawJhKB84fGEWyfANjjVKzUVgo.jpg",
    genre: ["Crimen", "Drama", "Thriller"],
    year: 1991,
    duration: 118,
    rating: 8.6,
    director: "Jonathan Demme",
    cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine"],
    trailer: "https://www.youtube.com/watch?v=W6Mm8Sbe__o"
  },
  {
    title: "Gladiador",
    description: "Un general romano es traicionado y su familia asesinada por el corrupto hijo del emperador. Reducido a la esclavitud, se convierte en gladiador para vengarse.",
    shortDescription: "Un general romano convertido en gladiador busca venganza contra el emperador corrupto.",
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
    genre: ["Acción", "Drama", "Aventura"],
    year: 2000,
    duration: 155,
    rating: 8.5,
    director: "Ridley Scott",
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
    trailer: "https://www.youtube.com/watch?v=owK1qxDselE"
  },
  {
    title: "El Club de la Pelea",
    description: "Un oficinista insomne y un fabricante de jabón forman un club de pelea clandestino que evoluciona en algo mucho más.",
    shortDescription: "Un club de pelea clandestino evoluciona hacia algo inesperado.",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg",
    genre: ["Drama"],
    year: 1999,
    duration: 139,
    rating: 8.8,
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
    trailer: "https://www.youtube.com/watch?v=qtRKdVHc-cE"
  },
  {
    title: "Star Wars: El Imperio Contraataca",
    description: "Después de que los rebeldes son derrotados en el planeta helado Hoth, Luke Skywalker comienza su entrenamiento Jedi con Yoda mientras sus amigos son perseguidos por Darth Vader.",
    shortDescription: "Los rebeldes huyen mientras Luke entrena para convertirse en Jedi.",
    poster: "https://image.tmdb.org/t/p/w500/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/3nYlM34QhzdtAvWRV5bN4nLtnTc.jpg",
    genre: ["Aventura", "Acción", "Ciencia ficción"],
    year: 1980,
    duration: 124,
    rating: 8.7,
    director: "Irvin Kershner",
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Billy Dee Williams"],
    trailer: "https://www.youtube.com/watch?v=JNwNXF9Y6kY"
  },
  {
    title: "Volver al Futuro",
    description: "Un adolescente viaja accidentalmente treinta años al pasado en un DeLorean modificado y debe asegurarse de que sus padres se enamoren o dejará de existir.",
    shortDescription: "Un adolescente viaja al pasado y debe asegurar que sus padres se enamoren.",
    poster: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4iKnCfAjeymkypJHGO7p1V2w6bB.jpg",
    genre: ["Aventura", "Comedia", "Ciencia ficción"],
    year: 1985,
    duration: 116,
    rating: 8.5,
    director: "Robert Zemeckis",
    cast: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
    trailer: "https://www.youtube.com/watch?v=qvsgGtivCgs"
  },
  {
    title: "El Señor de los Anillos: Las Dos Torres",
    description: "Mientras Frodo y Sam continúan su camino hacia Mordor, la comunidad rota debe enfrentar nuevas amenazas mientras las fuerzas de Saruman atacan.",
    shortDescription: "La comunidad separada enfrenta nuevas amenazas en su lucha contra el mal.",
    poster: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ctOEhQiFIHWkiaYp7b0ibSTe5IL.jpg",
    genre: ["Aventura", "Fantasía", "Acción"],
    year: 2002,
    duration: 179,
    rating: 8.7,
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Sean Astin"],
    trailer: "https://www.youtube.com/watch?v=LbfMDwc4azU"
  },
  {
    title: "El Señor de los Anillos: El Retorno del Rey",
    description: "Gandalf y Aragorn lideran el mundo de los hombres contra el ejército de Sauron para distraer su atención de Frodo y Sam mientras se acercan al Monte del Destino.",
    shortDescription: "La batalla final por la Tierra Media mientras Frodo completa su misión.",
    poster: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    genre: ["Aventura", "Fantasía", "Acción"],
    year: 2003,
    duration: 201,
    rating: 9.0,
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Orlando Bloom"],
    trailer: "https://www.youtube.com/watch?v=r7l0Rq9E8MY"
  },
  {
    title: "Los Vengadores",
    description: "Los héroes más poderosos de la Tierra deben unirse y aprender a luchar como un equipo si quieren detener a Loki y su ejército alienígena de esclavizar a la humanidad.",
    shortDescription: "Los héroes más poderosos de la Tierra se unen para salvar al mundo.",
    poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hbn46fQaRmlpBuUrEiFqv0GDL6Y.jpg",
    genre: ["Ciencia ficción", "Acción", "Aventura"],
    year: 2012,
    duration: 143,
    rating: 8.0,
    director: "Joss Whedon",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    trailer: "https://www.youtube.com/watch?v=eOrNdBpGMv8"
  },
  {
    title: "Buscando a Nemo",
    description: "Un pez payaso tímido emprende una búsqueda épica a través del océano para encontrar a su hijo que ha sido capturado por buzos.",
    shortDescription: "Un padre pez busca a su hijo perdido en el vasto océano.",
    poster: "https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/s6sJ8sAlZTimMu5GreHMSmFvRGO.jpg",
    genre: ["Animación", "Familia", "Aventura"],
    year: 2003,
    duration: 100,
    rating: 8.2,
    director: "Andrew Stanton",
    cast: ["Albert Brooks", "Ellen DeGeneres", "Alexander Gould", "Willem Dafoe"],
    trailer: "https://www.youtube.com/watch?v=wZdpNglLbt8"
  },
  {
    title: "Toy Story",
    description: "Los juguetes de un niño cobran vida cuando él no está. Cuando un nuevo juguete espacial llega, el vaquero favorito del niño teme ser reemplazado.",
    shortDescription: "Los juguetes cobran vida y el vaquero Woody teme ser reemplazado.",
    poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6yFoLNQgFdVbA8TZMdfgVpszOla.jpg",
    genre: ["Animación", "Aventura", "Familia", "Comedia"],
    year: 1995,
    duration: 81,
    rating: 8.3,
    director: "John Lasseter",
    cast: ["Tom Hanks", "Tim Allen", "Don Rickles", "Jim Varney"],
    trailer: "https://www.youtube.com/watch?v=v-PjgYDrg70"
  },
  {
    title: "Coco",
    description: "Un niño mexicano que sueña con ser músico se embarca en un viaje extraordinario al mágico mundo de sus ancestros durante el Día de los Muertos.",
    shortDescription: "Un niño viaja al mundo de los muertos para descubrir su historia familiar.",
    poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
    genre: ["Familia", "Animación", "Fantasía", "Música"],
    year: 2017,
    duration: 105,
    rating: 8.4,
    director: "Lee Unkrich",
    cast: ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"],
    trailer: "https://www.youtube.com/watch?v=Rvr68u6k5sI"
  },
  {
    title: "Spider-Man: Un Nuevo Universo",
    description: "El adolescente Miles Morales se convierte en Spider-Man y debe unirse a otros Spider-People de diferentes dimensiones para detener una amenaza.",
    shortDescription: "Miles Morales conoce a Spider-People de otros universos.",
    poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nk11pvocdb5zbFhX5oq5YiLPYMo.jpg",
    genre: ["Acción", "Aventura", "Animación", "Ciencia ficción"],
    year: 2018,
    duration: 117,
    rating: 8.4,
    director: "Bob Persichetti, Peter Ramsey",
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
    trailer: "https://www.youtube.com/watch?v=tg52up16eq0"
  },
  {
    title: "Jurassic Park",
    description: "Durante un recorrido por un parque temático de dinosaurios clonados, una falla en la seguridad libera a los depredadores y los visitantes deben sobrevivir.",
    shortDescription: "Un parque de dinosaurios se convierte en pesadilla cuando los animales escapan.",
    poster: "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/lw3099h7XoBGXWKCK45tn5y5P8w.jpg",
    genre: ["Aventura", "Ciencia ficción"],
    year: 1993,
    duration: 127,
    rating: 8.2,
    director: "Steven Spielberg",
    cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum", "Richard Attenborough"],
    trailer: "https://www.youtube.com/watch?v=lc0UehYemQA"
  },
  {
    title: "Salvando al Soldado Ryan",
    description: "Tras el desembarco de Normandía, un grupo de soldados estadounidenses se adentra en territorio enemigo para encontrar a un paracaidista cuya familia ha sufrido grandes pérdidas.",
    shortDescription: "Soldados buscan a un paracaidista en la Francia ocupada por los nazis.",
    poster: "https://image.tmdb.org/t/p/w500/uqx37vjwi8H4A7flbwtr8rxH88k.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/qOoZ9fVBhsgMaJvzGsHjhUiZDf.jpg",
    genre: ["Drama", "Historia", "Guerra"],
    year: 1998,
    duration: 169,
    rating: 8.6,
    director: "Steven Spielberg",
    cast: ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns"],
    trailer: "https://www.youtube.com/watch?v=9CiW_DgxCnQ"
  },
  {
    title: "Seven",
    description: "Dos detectives, uno veterano y otro novato, persiguen a un asesino en serie que utiliza los siete pecados capitales como motivo para sus asesinatos.",
    shortDescription: "Detectives persiguen a un asesino que usa los siete pecados capitales.",
    poster: "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ewlwqJGNyc0bGEZrLKO5bZCnm8G.jpg",
    genre: ["Crimen", "Misterio", "Thriller"],
    year: 1995,
    duration: 127,
    rating: 8.6,
    director: "David Fincher",
    cast: ["Morgan Freeman", "Brad Pitt", "Kevin Spacey", "Gwyneth Paltrow"],
    trailer: "https://www.youtube.com/watch?v=znmZoVkCjpI"
  },
  {
    title: "El Resplandor",
    description: "Una familia se muda a un hotel aislado para el invierno donde una presencia siniestra influye al padre hacia la violencia, mientras su hijo psíquico ve horrorosos presagios.",
    shortDescription: "Un hotel aislado desata la locura en un escritor y su familia.",
    poster: "https://image.tmdb.org/t/p/w500/xazWoLealQwEgqZ89MLZklLZD3k.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/l8j0njJRbEaiwR2FMVxlJp7B5jO.jpg",
    genre: ["Horror", "Thriller"],
    year: 1980,
    duration: 146,
    rating: 8.4,
    director: "Stanley Kubrick",
    cast: ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
    trailer: "https://www.youtube.com/watch?v=5Cb3ik6zP2I"
  },
  {
    title: "Tiburón",
    description: "Cuando un gran tiburón blanco comienza a aterrorizar a un pueblo costero, un jefe de policía, un biólogo marino y un cazador de tiburones deben detenerlo.",
    shortDescription: "Un tiburón asesino aterroriza un pueblo costero.",
    poster: "https://image.tmdb.org/t/p/w500/lxT3LqAFXo3BFOzHlcwkupcjSjh.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/eU4OqYKr6Cb64bEJhzrFYJpH4uD.jpg",
    genre: ["Horror", "Thriller", "Aventura"],
    year: 1975,
    duration: 124,
    rating: 8.1,
    director: "Steven Spielberg",
    cast: ["Roy Scheider", "Robert Shaw", "Richard Dreyfuss", "Lorraine Gary"],
    trailer: "https://www.youtube.com/watch?v=U1fu_sA7XhE"
  },
  {
    title: "El Pianista",
    description: "Un pianista judío polaco lucha por sobrevivir durante la destrucción del gueto de Varsovia en la Segunda Guerra Mundial.",
    shortDescription: "Un pianista judío lucha por sobrevivir durante el Holocausto.",
    poster: "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/6lj1TrH7I6GA0qNS7sV7bqWuNqo.jpg",
    genre: ["Drama", "Guerra"],
    year: 2002,
    duration: 150,
    rating: 8.5,
    director: "Roman Polanski",
    cast: ["Adrien Brody", "Thomas Kretschmann", "Frank Finlay", "Emilia Fox"],
    trailer: "https://www.youtube.com/watch?v=BFwGqLa_oAo"
  },
  {
    title: "La Vida es Bella",
    description: "Un padre judío italiano usa su imaginación para proteger a su hijo de los horrores de un campo de concentración nazi.",
    shortDescription: "Un padre protege a su hijo en un campo de concentración con humor e imaginación.",
    poster: "https://image.tmdb.org/t/p/w500/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bORe0eI72D874TMawAgpC6zgZjM.jpg",
    genre: ["Comedia", "Drama"],
    year: 1997,
    duration: 116,
    rating: 8.6,
    director: "Roberto Benigni",
    cast: ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini", "Giustino Durano"],
    trailer: "https://www.youtube.com/watch?v=pAYEQP8gx3w"
  },
  {
    title: "Amélie",
    description: "Una joven camarera parisina decide ayudar a los demás y mejorar sus vidas mientras lucha con su propia soledad.",
    shortDescription: "Una joven francesa encuentra felicidad ayudando a otros en París.",
    poster: "https://image.tmdb.org/t/p/w500/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2uXZyZsGxB1QKphjJ2gDjLS5VQK.jpg",
    genre: ["Comedia", "Romance"],
    year: 2001,
    duration: 122,
    rating: 8.3,
    director: "Jean-Pierre Jeunet",
    cast: ["Audrey Tautou", "Mathieu Kassovitz", "Rufus", "Lorella Cravotta"],
    trailer: "https://www.youtube.com/watch?v=eorR_EQdk7Q"
  },
  {
    title: "Django Sin Cadenas",
    description: "Con la ayuda de un cazarrecompensas alemán, un esclavo liberado se propone rescatar a su esposa de un brutal propietario de plantaciones en Misisipi.",
    shortDescription: "Un esclavo liberado busca rescatar a su esposa con la ayuda de un cazarrecompensas.",
    poster: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg",
    genre: ["Drama", "Western"],
    year: 2012,
    duration: 165,
    rating: 8.4,
    director: "Quentin Tarantino",
    cast: ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington"],
    trailer: "https://www.youtube.com/watch?v=eUdM9vrCbow"
  },
  {
    title: "Bastardos sin Gloria",
    description: "En la Francia ocupada por los nazis, un grupo de soldados judíos estadounidenses, conocidos como 'Los Bastardos', planea asesinar a líderes nazis.",
    shortDescription: "Soldados judíos planean un ataque contra líderes nazis en Francia.",
    poster: "https://image.tmdb.org/t/p/w500/vDwqPyhkzFPRDmHq8RXocTS7xGr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ar2h87jlTfRjr7jMdw5hI0H6F8j.jpg",
    genre: ["Drama", "Acción", "Thriller", "Guerra"],
    year: 2009,
    duration: 153,
    rating: 8.3,
    director: "Quentin Tarantino",
    cast: ["Brad Pitt", "Mélanie Laurent", "Christoph Waltz", "Eli Roth"],
    trailer: "https://www.youtube.com/watch?v=6td8cKDH1SE"
  },
  {
    title: "Whiplash",
    description: "Un joven baterista ambicioso es empujado al límite por su instructor de conservatorio abusivo en busca de la grandeza.",
    shortDescription: "Un baterista es empujado al límite por su instructor obsesivo.",
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fRdwzP94MeqVdFFyDQyvJcIB8Sp.jpg",
    genre: ["Drama", "Música"],
    year: 2014,
    duration: 106,
    rating: 8.5,
    director: "Damien Chazelle",
    cast: ["Miles Teller", "J.K. Simmons", "Melissa Benoist", "Paul Reiser"],
    trailer: "https://www.youtube.com/watch?v=7d_jQycdQGo"
  },
  {
    title: "La La Land",
    description: "Mientras navegan por sus carreras en Los Ángeles, una aspirante a actriz y un músico de jazz dedicado comienzan un romance apasionado.",
    shortDescription: "Un romance musical entre una actriz y un músico de jazz en Los Ángeles.",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fp6X6yhgcxzxCpmM0EZP3PiOCIN.jpg",
    genre: ["Comedia", "Drama", "Romance", "Música"],
    year: 2016,
    duration: 128,
    rating: 8.0,
    director: "Damien Chazelle",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
    trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8"
  },
  {
    title: "Joker",
    description: "En Gotham City, Arthur Fleck, un comediante fallido, se transforma en el Joker, el icónico villano criminal.",
    shortDescription: "La transformación de un hombre en el icónico villano Joker.",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    genre: ["Crimen", "Thriller", "Drama"],
    year: 2019,
    duration: 122,
    rating: 8.4,
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy"],
    trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY"
  },
  {
    title: "Black Panther",
    description: "T'Challa, heredero del reino escondido de Wakanda, debe asumir el trono y liderar su nación hacia un nuevo futuro.",
    shortDescription: "El rey de Wakanda debe defender su nación de enemigos externos e internos.",
    poster: "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    year: 2018,
    duration: 134,
    rating: 7.3,
    director: "Ryan Coogler",
    cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira"],
    trailer: "https://www.youtube.com/watch?v=xjDjIWPwcPU"
  },
  {
    title: "Mad Max: Furia en el Camino",
    description: "En un futuro apocalíptico, Max se une a Furiosa para escapar de un tirano y su ejército en una carrera por el desierto.",
    shortDescription: "Una persecución épica en un mundo post-apocalíptico.",
    poster: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tbhdm8UJAb4ViCTsulYFL3lxMCd.jpg",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    year: 2015,
    duration: 120,
    rating: 8.1,
    director: "George Miller",
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
    trailer: "https://www.youtube.com/watch?v=hEJnMQG9ev8"
  },
  {
    title: "Harry Potter y la Piedra Filosofal",
    description: "Un niño huérfano descubre que es un mago en su undécimo cumpleaños cuando es invitado a asistir a la Escuela de Magia y Hechicería de Hogwarts.",
    shortDescription: "Un niño descubre que es un mago y asiste a una escuela de magia.",
    poster: "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
    genre: ["Aventura", "Fantasía"],
    year: 2001,
    duration: 152,
    rating: 7.9,
    director: "Chris Columbus",
    cast: ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Richard Harris"],
    trailer: "https://www.youtube.com/watch?v=VyHV0BRtdxo"
  },
  {
    title: "Spider-Man: No Way Home",
    description: "Con la identidad de Spider-Man revelada, Peter pide ayuda al Doctor Strange. Cuando un hechizo sale mal, peligrosos enemigos de otros mundos comienzan a aparecer.",
    shortDescription: "Spider-Man enfrenta villanos de universos alternos tras revelar su identidad.",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    genre: ["Acción", "Aventura", "Ciencia ficción"],
    year: 2021,
    duration: 148,
    rating: 8.2,
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon"],
    trailer: "https://www.youtube.com/watch?v=JfVOs4VSpmA"
  },
  {
    title: "Oppenheimer",
    description: "La historia del físico teórico J. Robert Oppenheimer y su papel en el desarrollo de la bomba atómica durante el Proyecto Manhattan.",
    shortDescription: "La vida del físico que creó la bomba atómica.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    genre: ["Drama", "Historia"],
    year: 2023,
    duration: 180,
    rating: 8.3,
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    trailer: "https://www.youtube.com/watch?v=uYPbbksJxIg"
  },
  {
    title: "Barbie",
    description: "Después de ser expulsada de Barbieland por ser una muñeca de aspecto menos que perfecto, Barbie parte hacia el mundo humano para encontrar la verdadera felicidad.",
    shortDescription: "Barbie explora el mundo real en busca del verdadero significado de ser perfecta.",
    poster: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
    genre: ["Comedia", "Aventura", "Fantasía"],
    year: 2023,
    duration: 114,
    rating: 7.1,
    director: "Greta Gerwig",
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera", "Kate McKinnon"],
    trailer: "https://www.youtube.com/watch?v=pBk4NYhWNMM"
  },
  {
    title: "El Hombre Araña: A Través del Spider-Verso",
    description: "Miles Morales regresa para una aventura épica que transportará al amigable vecino de Brooklyn a través del Multiverso.",
    shortDescription: "Miles Morales viaja a través del Multiverso enfrentando nuevos desafíos.",
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hhvK5cPskBPp5C1qwHFqKOa2oiN.jpg",
    genre: ["Animación", "Acción", "Aventura", "Ciencia ficción"],
    year: 2023,
    duration: 140,
    rating: 8.7,
    director: "Joaquim Dos Santos, Kemp Powers",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Brian Tyree Henry", "Oscar Isaac"],
    trailer: "https://www.youtube.com/watch?v=cqGjhVJWtEg"
  },
  {
    title: "Avatar: El Camino del Agua",
    description: "Jake Sully vive con su nueva familia formada en el planeta de Pandora. Una vez una amenaza familiar regresa, Jake debe trabajar con Neytiri y el ejército para proteger su planeta.",
    shortDescription: "Jake Sully debe proteger Pandora de una nueva amenaza.",
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    genre: ["Ciencia ficción", "Aventura", "Acción"],
    year: 2022,
    duration: 192,
    rating: 7.6,
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Kate Winslet"],
    trailer: "https://www.youtube.com/watch?v=d9MyW72ELq0"
  },
  {
    title: "Guardianes de la Galaxia",
    description: "Un grupo de delincuentes intergalácticos debe unirse para evitar que un villano fanático obtenga un poderoso artefacto.",
    shortDescription: "Un grupo de inadaptados se une para salvar la galaxia.",
    poster: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bHarw8xrmQeqf3t8HpuMY7zoK4x.jpg",
    genre: ["Acción", "Ciencia ficción", "Aventura"],
    year: 2014,
    duration: 121,
    rating: 8.0,
    director: "James Gunn",
    cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Vin Diesel"],
    trailer: "https://www.youtube.com/watch?v=d96cjJhvlMA"
  }
]

export default seedMovies
